const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.gamepad,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.Platform,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.LOS,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Behaviors.LOS.Acts.CastRay,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Behaviors.LOS.Exps.Range,
		C3.Behaviors.LOS.Cnds.RayIntersected,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.LOS.Exps.HitDistance,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetLayerEffectParam,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceWidth,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Behaviors.Bullet.Acts.SetBounceOffSolids,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Gamepad: 0},
	{Keyboard: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Tween: 0},
	{Timer: 0},
	{GameManager: 0},
	{PlatformInfo: 0},
	{Fade: 0},
	{TextFont: 0},
	{JumpingDust: 0},
	{LandingDust: 0},
	{AirStomp: 0},
	{LastX: 0},
	{LastY: 0},
	{Platform: 0},
	{PlayerCollision: 0},
	{PlayerGraphics: 0},
	{WalkingDust: 0},
	{ShockTrail: 0},
	{BlockShock: 0},
	{ShockAirParticles: 0},
	{ShockFeet: 0},
	{ShockGlow: 0},
	{ShockImpact: 0},
	{ZShapedShock: 0},
	{Background: 0},
	{Solid: 0},
	{Ground: 0},
	{LineOfSight: 0},
	{Flash: 0},
	{Spike: 0},
	{TeleportPlatformFront: 0},
	{Charged: 0},
	{TeleportTrigger: 0},
	{Block: 0},
	{BlockCollision: 0},
	{Bullet: 0},
	{BlockDebris: 0},
	{TeleportPlatformBack: 0},
	{TARGETFRAMERATE: 0},
	{DEFAULTLAYOUTSCALE: 0},
	{InputLeft: 0},
	{InputRight: 0},
	{InputUp: 0},
	{InputDown: 0},
	{HorizontalAxis: 0},
	{VerticalAxis: 0},
	{AxisAngle: 0},
	{PositionX: 0},
	{PositionY: 0},
	{CurrentPosX: 0},
	{CurrentPosY: 0},
	{NextPosX: 0},
	{NextPosY: 0},
	{CurrentAngle: 0},
	{DEFAULTWIDTH: 0},
	{SpawnPosX: 0},
	{SpawnPosY: 0},
	{SpawnAngle: 0},
	{CAMERASPEED: 0},
	{CAMERAOFFSETX: 0},
	{CAMERAOFFSETY: 0},
	{Intensity: 0},
	{Duration: 0},
	{BlockUID: 0},
	{SCROLLINGSPEED: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Camera: class extends self.ISpriteInstance {},
	GameManager: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	JumpingDust: class extends self.ISpriteInstance {},
	LandingDust: class extends self.ISpriteInstance {},
	PlayerCollision: class extends self.ISpriteInstance {},
	PlayerGraphics: class extends self.ISpriteInstance {},
	WalkingDust: class extends self.ISpriteInstance {},
	ShockTrail: class extends self.ISpriteInstance {},
	BlockShock: class extends self.ISpriteInstance {},
	ShockAirParticles: class extends self.IParticlesInstance {},
	ShockFeet: class extends self.ISpriteInstance {},
	ShockGlow: class extends self.ISpriteInstance {},
	ShockImpact: class extends self.ISpriteInstance {},
	ZShapedShock: class extends self.ISpriteInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	Ground: class extends self.ITilemapInstance {},
	Flash: class extends self.ITiledBackgroundInstance {},
	Spike: class extends self.ISpriteInstance {},
	TeleportPlatformFront: class extends self.ISpriteInstance {},
	TeleportTrigger: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {},
	BlockCollision: class extends self.ISpriteInstance {},
	BlockDebris: class extends self.ISpriteInstance {},
	TeleportPlatformBack: class extends self.ISpriteInstance {}
}